// Robots policy generated by Next 16 metadata route at /robots.txt. Explicit
// friendlier rules for AI crawlers so we ship a concrete stance instead of
// silence (GPTBot/ClaudeBot/CCBot) — review quarterly as policy evolves.
// Docs: https://nextjs.org/docs/app/api-reference/file-conventions/metadata/robots.
import type { MetadataRoute } from 'next';
import { getSiteUrl } from '@blue-escrow/config';

export default function robots(): MetadataRoute.Robots {
  const base = getSiteUrl().toString().replace(/\/$/, '');

  return {
    rules: [
      {
        userAgent: '*',
        allow: '/',
        disallow: ['/app/api/', '/_next/', '/private/'],
      },
      // AI training/scraping bots — explicitly allowed to crawl the marketing
      // surface. Flip to disallow: ['/'] here if the team's stance changes.
      {
        userAgent: ['GPTBot', 'CCBot', 'ClaudeBot'],
        allow: '/',
        disallow: ['/app/api/', '/_next/', '/private/'],
      },
    ],
    sitemap: `${base}/sitemap.xml`,
    host: base,
  };
}
