import baseConfig from '@blue-escrow/eslint-config';

export default [
  ...baseConfig,
  {
    // Generated by `prisma generate` — never hand-edit, never lint.
    ignores: ['src/generated/'],
  },
];
